site_name: Conflict Monitoring - NTL
site_url: https://dummy.org/
extra_css:
  - stylesheets/extra.css

nav:
  - Analysis:
      - Satellites: analysis/satellites.md
      - Quantification: analysis/quantification.md
      - Regions: notebooks/cities.ipynb
      - Plotting: notebooks/plotting.ipynb
  - System Design:
      - SDK: system_design/sdk.md
  - User Guide:
      - Compare Images: notebooks/example_comparison.ipynb

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - toc.integrate
    - navigation.sections
    - content.tooltips
    - content.footnote.tooltips
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

plugins:
  - search
  - mkdocs-jupyter
  - panzoom
  - d2
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - abbr
  - attr_list
  - pymdownx.snippets
  - footnotes
