site_name: Conflict Monitoring - NTL
site_url: https://dummy.org/
theme:
  name: material
  features:
    - navigation.sections

nav:
  - Analysis:
      - Satellites: analysis/satellites.md
  - User Guide:
      - Exploration: ../notebooks/exploration.ipynb
      
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
